// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asm5.Models;

#nullable disable

namespace asm5.Migrations
{
    [DbContext(typeof(BookDbContext))]
    partial class BookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("asm5.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Nguyễn Nhật Ánh",
                            CategoryId = 1,
                            Description = "Cho tôi xin một vé đi tuổi thơ là một trong những tác phẩm thành công nhất của nhà văn Nguyễn Nhật Ánh. Cuốn sách mở ra một thế giới đầy trong trẻo, hồn nhiên của tuổi thơ và đồng thời cũng gợi lên những suy ngẫm sâu sắc cho người lớn về cách giáo dục và hiểu tâm lý con trẻ.",
                            Image = "cho-toi-xin-mot-ve-di-tuoi-tho.png",
                            Price = 61600m,
                            Title = "Cho tôi xin một vé đi tuổi thơ"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Hải Dở",
                            CategoryId = 1,
                            Description = "Đàn ông tuổi 18 mơ ước thành đàn ông tuổi 20, đàn ông tuổi 20 mơ ước thành đàn ông tuổi 30, đàn ông tuổi 30 mơ ước trở thành đàn ông tuổi 40 và đàn ông tuổi 40 lại mơ ước dứt chân lên cỗ máy thời gian để quay lại tuổi 20 với toàn bộ tài sản của mình! Vậy đấy!",
                            Image = "cuoc-song-rat-giong-cuoc-doi.png",
                            Price = 61000m,
                            Title = "Cuộc sống rất giống cuộc đời"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Cay S. Horstmann",
                            CategoryId = 2,
                            Description = "Cuốn sách cung cấp kiến thức nền tảng vững chắc về ngôn ngữ lập trình Java, bao gồm cú pháp cơ bản, hướng đối tượng, xử lý ngoại lệ, và các tính năng cốt lõi của JDK.",
                            Image = "core-java.png",
                            Price = 120000m,
                            Title = "Core Java Fundamentals, Volume 1"
                        });
                });

            modelBuilder.Entity("asm5.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Cuộc sống"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Lập trình"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sức khỏe"
                        });
                });

            modelBuilder.Entity("asm5.Models.Book", b =>
                {
                    b.HasOne("asm5.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("asm5.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
